<?php

return array(
    'shipping_title' => 'Shipping & Payment',
    'shipping_text' => '<p>The shipment of your order is being processed by acknowledged, reliable and qualitative courier services only. When ordering a single or few CamHatches, your order can almost certainly be delivered in your letterbox, therefore you don’t need to wait at home in order to receive your order.</p><br><p>Your delivery options will be displayed on the checkout page and will be worked out depending on your checkout shopping basket. Shipping is carefully calculated on the weight, size and value of your order, so the options can vary depending on what you have purchased. The simplest way to see is to head through to the checkout and enter your delivery address/country; we’ll automatically show you the wide variety of available options you have, don’t worry, you won’t be charged.</p><br><p>We offer various ways to pay for our items, including iDEAL and PayPal, to ensure that as many of our international customers as possible can access and purchase our privacy solutions. Your preferred payment method of choice can be selected at the checkout.
As soon as we have received your payment, we proceed to the shipment of your order.</p>',

    'warranty_title' => 'Warranty Policy',
    'warranty_text' => '<p>Because we are sure of the quality of our products, we offer you an extra-long time for reflection of 30 days instead of the legal 14 days. This means that you have 30 days to send us back the purchased goods undamaged and in their original packing to this address:</p><br><p><b>CamHatch Netherlands B.V.</b><br>Adriaen van der Doeslaand 115C<br>3054 RB Rotterdam<br>Netherlands<br><br>CoC-number:: 68452462<br>VaT-number:: NL857450712B01</p><br><b>Faulty CamHatch</b><br><p>CamHatch focuses on quality products. However, if you’re unlucky to receive a faulty product, or if your CamHatch breaks, please send us an email  (<a href="mailto:info@camhatch.com">info@camhatch.com</a>) with pictures of the broken CamHatch along with your order number. We will contact you for further instructions.</p>',

    'stores_title' => 'stores',
    'stores_text' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper lacus. Maecenas vehicula luctus pulvinar. Phasellus ac mi quis lorem finibus lobortis. Vivamus nec erat metus. Duis a lacus laoreet, interdum erat sit amet, consequat est. Aenean sit amet nibh non libero malesuada sagittis. Nulla maximus dui sit amet nulla mattis, iaculis ultricies purus interdum. Curabitur ut sodales massa, ut hendrerit orci.</p><p>Donec dictum, erat congue sollicitudin posuere, dolor dui ultrices neque, a finibus metus lectus vel neque. Aliquam euismod sed leo vel porttitor. Nullam consectetur dui ac convallis facilisis. Vivamus nec quam sed massa posuere interdum vitae id urna. Pellentesque laoreet dolor massa, id tempus magna dictum sed. Ut suscipit, ipsum eget interdum egestas, nulla erat dictum sem, sed cursus odio risus vitae orci. Fusce aliquam urna metus, in interdum enim condimentum et. Donec laoreet nunc a aliquam feugiat. Aenean vel congue leo. Cras luctus arcu sed purus ornare accumsan.</p>'
);
