<?php

return array(
    'shipping_title' => 'Betalen & Verzenden',
    'shipping_text' => '<p>De verzending van uw bestelling wordt alleen uitgevoerd door erkende, betrouwbare en kwalitatieve koeriersdiensten. Wanneer slechts één of enkele CamHatches worden besteld, dan kan uw bestelling hoogstwaarschijnlijk simpelweg in uw brievenbus geleverd worden zodat u niet thuis hoeft te wachten om uw pakket te ontvangen!</p><br><p>Voor zendingen met een waarde onder de € 50, rekenen wij extra verzendkosten van € 2,50 voor verzending naar België (€ 7,26 internationale levering). Bedraagt uw bestelling meer dan € 50? Dan wordt uw pakket verstuurd zonder extra kosten!</p><br><p>Als het gaat om de betaling van de producten die u hebt besteld via onze webshop, zijn er tal van mogelijkheden. Het is onder andere mogelijk om te betalen met een creditcard (Mastercard en Visa) en door middel van uw PayPal-rekening. U kunt ook altijd betalen met een klassieke overschrijving. Zodra we de betaling ontvangen hebben, gaan we door naar de verzending van uw bestelling. In geval van een betaling via overschrijving, kan dit een paar dagen in beslag nemen, afhankelijk van de bankinstelling. Om uw bestelling sneller te laten leveren, helpt het ons om uw bewijs van betaling te bezorgen. Op deze manier hoeven we niet te wachten op uw betaling en hebt u uw bestelling veel sneller bij u thuis!</p>',

    'warranty_title' => 'Garantievoorwaarden',
    'warranty_text' => '<p>Omdat we zeker zijn van de kwaliteit van ons product, bieden we je 30 dagen bedenktijd in plaats van de wettelijke 14 dagen. Dit betekent dat je 30 dagen hebt om ons het product onbeschadigd en in originele verpakking terug te sturen naar dit adres:</p><br><p><b>CamHatch Netherlands B.V.</b><br>Adriaen van der Doeslaan 115C<br>3054 EB Rotterdam<br>Netherlands<br><br>CoC-number:: 68452462<br>VaT-number:: NL857450712B01</p><br><p><b>Defecte CamHatch</b><br>CamHatch staat in voor de kwaliteit van haar producten. Is je CamHatch toch defect geraakt of heb of heb jij net de pech om een defecte CamHatch te ontvangen, stuur ons dan een foto van de CamHatch samen met je ordernummer naar <a href="mailto:info@camhatch.com">info@camhatch.com</a>. Dan contacteren we je verder.</p>',

    'stores_title' => 'stores',
    'stores_text' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper lacus. Maecenas vehicula luctus pulvinar. Phasellus ac mi quis lorem finibus lobortis. Vivamus nec erat metus. Duis a lacus laoreet, interdum erat sit amet, consequat est. Aenean sit amet nibh non libero malesuada sagittis. Nulla maximus dui sit amet nulla mattis, iaculis ultricies purus interdum. Curabitur ut sodales massa, ut hendrerit orci.</p><p>Donec dictum, erat congue sollicitudin posuere, dolor dui ultrices neque, a finibus metus lectus vel neque. Aliquam euismod sed leo vel porttitor. Nullam consectetur dui ac convallis facilisis. Vivamus nec quam sed massa posuere interdum vitae id urna. Pellentesque laoreet dolor massa, id tempus magna dictum sed. Ut suscipit, ipsum eget interdum egestas, nulla erat dictum sem, sed cursus odio risus vitae orci. Fusce aliquam urna metus, in interdum enim condimentum et. Donec laoreet nunc a aliquam feugiat. Aenean vel congue leo. Cras luctus arcu sed purus ornare accumsan.</p>'
);
